### PR TITLE
Release: v2.0.0

### PR DESCRIPTION
**Pull request by NilsDelaguardia**

### CODE REVIEW

**Review by iBotPeaches — DISMISSED** [review]
Not sure how I feel about ticket numbers in open source, they don't mean much to public and yet they help us.

**Review by nicomaurer — APPROVED** [review]

**Comment by nicomaurer** [comment]
> Not sure how I feel about ticket numbers in open source, they don't mean much to public and yet they help us.

@iBotPeaches Would dropping the ticket numbers and combining some of them be better? 🤔

**Comment by iBotPeaches** [comment]
> @iBotPeaches Would dropping the ticket numbers and combining some of them be better? 🤔

Lets kill them and figure out a good solution for open source projects for what we do about this.

**Review by iBotPeaches — APPROVED** [review]
thanks, squash merge when ready

**Review by nicomaurer — APPROVED** [review]

**Comment by nicomaurer** [comment]
> > @iBotPeaches Would dropping the ticket numbers and combining some of them be better? 🤔
> 
> Lets kill them and figure out a good solution for open source projects for what we do about this.

Gotcha, just find the two PHP upgrade notes a bit weird to have them separated in my opinion.

**Review by Jasonej — APPROVED** [review]

**Review by erik-perri — APPROVED** [review]

**Review by frankspress — APPROVED** [review]

**Pull request merged**
