### PR TITLE
SIP-131 update: Support for PHP 8.1

### PR DESCRIPTION
**Pull request by NilsDelaguardia**

### CODE REVIEW

**Comment by iBotPeaches** [comment]
If you need to drop old PHP and make a new major version - lets do it. The API is steady in this so I don't mind a new major version to drop some old PHP versions as that upgrade path is still easy.

**Review by Jasonej — APPROVED** [review]

**Review by frankspress — APPROVED** [review]

**Review by iBotPeaches — DISMISSED** [review]
Cool. Make a v2 major after this is good and tag it, etc.

**Review by nicomaurer — DISMISSED** [review]

**Comment by iBotPeaches** [comment]
(well build failing now, but point still good)

**Review by nicomaurer — APPROVED** [review]

**Review by erik-perri — APPROVED** [review]

**Review by iBotPeaches — APPROVED** [review]

**Comment by NilsDelaguardia** [comment]
> Cool. Make a v2 major after this is good and tag it, etc.

Think we could add this Laravel 9 support ticket as well in that release. https://sourcetoad.atlassian.net/browse/SIP-229

**Comment by iBotPeaches** [comment]
> > Cool. Make a v2 major after this is good and tag it, etc.
> 
> Think we could add this Laravel 9 support ticket as well in that release. https://sourcetoad.atlassian.net/browse/SIP-229

yep sounds good, defer it till that

**Review by frankspress — APPROVED** [review]

**Pull request merged**
